language: python
sudo: false

python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"

env:
  - DJANGO="django==3.2.9"
  - DJANGO="django==3.0.5"
  - DJANGO="django==2.0"
  - DJANGO="django==1.10"
  - DJANGO="django==1.9"
  - DJANGO="django==1.8.7"

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django==3.0.5"
    - python: "3.5"
      env: DJANGO="django==3.0.5"
    - python: "3.4"
      env: DJANGO="django==3.2.9"
    - python: "3.5"
      env: DJANGO="django==3.2.9"

install:
  - pip install $DJANGO
  - pip install django-jinja

script:
  - python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
