name: Test Django-Sites

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        python-version: ["3.4", "3.5", "3.6", "3.7", "3.8", "3.9"]
        django-version: ["1.8.7", "1.9", "1.10", "2.0", "3.0.5", "3.2.9"]
        exclude:
          - python-version: "3.4"
            django-version: "django==3.0.5"
          - python-version: "3.5"
            django-version: "django==3.0.5"
          - python-version: "3.4"
            django-version: "django==3.2.9"
          - python-version: "3.5"
            django-version: "django==3.2.9"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - name: Upgrade django version
        run: |
          python -m pip install "Django~=${{ matrix.django-version }}"

      - name: Run tests
        run: |
          ${{ matrix.python-version }} runtests.py
